swaks --server esa1.dcloud.cisco.com --from allowlist@cisco.com --to alan@dcloud.cisco.com --header "subject: Allow List test" --body "https://ihaveabadreputation.com test"
swaks --server esa1.dcloud.cisco.com --from no-allowlist@cisco.com --to alan@dcloud.cisco.com --header "subject: Allow List test" --body "https://ihaveabadreputation.com test"
swaks --server esa1.dcloud.cisco.com --from verdict@cisco.com --to alan@dcloud.cisco.com --header "subject: Verdict List test" --body "https://ihaveabadreputation.com test"
swaks --server esa1.dcloud.cisco.com --from no-verdict@cisco.com --to alan@dcloud.cisco.com --header "subject: Verdict List test" --body "https://ihaveabadreputation.com test"
swaks --server esa1.dcloud.cisco.com --from phishtest@cisco.com --to alan@dcloud.cisco.com --header "subject: Bypass List test" --body "https://ihaveabadreputation.com test"
swaks --server esa1.dcloud.cisco.com --from no-phishtest@cisco.com --to alan@dcloud.cisco.com --header "subject: Bypass List test" --body "https://ihaveabadreputation.com test"
swaks --server esa1.dcloud.cisco.com --from crobbins@dcloud.cisco.com --to alan@dcloud.cisco.com --header "From: Chuck Robbins <crobbins@dcloud.cisco.com>" --header "subject: VIP test" --body "https://ihaveabadreputation.com test"
